version: '2'

services:
  backend:
    image: 'carbackend:latest'
    build:
      context: .
    container_name: backend
    links:
      - "db:cardb"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/cardb
  db:
    image: 'mariadb:10.5'
    container_name: db
    environment:
      - MARIADB_ROOT_PASSWORD=1234567890
      - MARIADB_DATABASE=cardb
    ports: 
      - "3306:3306"
